-- Extensões (no Supabase vivem no schema "extensions")
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "unaccent" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pg_trgm" WITH SCHEMA extensions;

-- Normalização IMMUTABLE para índices de busca
CREATE OR REPLACE FUNCTION public.fn_norm(p_texto TEXT)
RETURNS TEXT LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT AS $$
    SELECT lower(extensions.unaccent('extensions.unaccent'::regdictionary, p_texto));
$$;

CREATE TYPE perfil_usuario_enum AS ENUM ('ADMIN','GERENTE','VENDEDOR','FINANCEIRO');
CREATE TYPE status_documento_enum AS ENUM ('RASCUNHO','CONFIRMADO','CANCELADO');
CREATE TYPE bucket_estoque_enum AS ENUM ('DISPONIVEL','RESERVADO','MOSTRUARIO','CONSIGNADO');
CREATE TYPE tipo_movimento_enum AS ENUM (
  'ENTRADA_COMPRA','SAIDA_VENDA','SAIDA_REMESSA','RETORNO_DEVOLUCAO',
  'BAIXA_VENDA_CONSIGNADA','BAIXA_PERDA','RESERVA','LIBERACAO_RESERVA',
  'AJUSTE_POSITIVO','AJUSTE_NEGATIVO','ESTORNO');
CREATE TYPE tipo_venda_enum AS ENUM ('CONSUMIDOR','REVENDEDOR');
CREATE TYPE tipo_remessa_enum AS ENUM ('MOSTRUARIO','CONSIGNACAO');
CREATE TYPE status_item_remessa_enum AS ENUM ('EM_POSSE','VENDIDO','DEVOLVIDO','PERDIDO','TROCADO');
CREATE TYPE situacao_titulo_enum AS ENUM ('ABERTO','PAGO','CANCELADO');
CREATE TYPE tipo_devedor_enum AS ENUM ('CLIENTE','REVENDEDOR');
CREATE TYPE origem_titulo_enum AS ENUM ('VENDA','PRESTACAO_CONTAS','AVULSO');
CREATE TYPE criterio_rateio_enum AS ENUM ('VALOR','QUANTIDADE');
CREATE TYPE categoria_despesa_enum AS ENUM (
  'PERDA_ESTOQUE','FRETE_ENVIO','TAXA_PAGAMENTO','EMBALAGEM',
  'MARKETING','COMISSAO','OPERACIONAL','OUTRAS');
CREATE TYPE natureza_despesa_enum AS ENUM ('FIXA','VARIAVEL');
CREATE TYPE acao_auditoria_enum AS ENUM ('INSERT','UPDATE','DELETE','CANCEL','LOGIN','LOGOUT','EXPORT');
CREATE TYPE severidade_enum AS ENUM ('INFO','ATENCAO','CRITICO');
CREATE TYPE tipo_notificacao_enum AS ENUM (
  'PARCELA_A_VENCER','PARCELA_VENCIDA','MOSTRUARIO_ANTIGO',
  'PRODUTO_PARADO','ESTOQUE_BAIXO','SISTEMA');
