CREATE TABLE public.usuarios (
    id            UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nome          TEXT NOT NULL CHECK (length(trim(nome)) BETWEEN 2 AND 120),
    email         TEXT NOT NULL,
    perfil        perfil_usuario_enum NOT NULL DEFAULT 'ADMIN',
    telefone      TEXT,
    ativo         BOOLEAN NOT NULL DEFAULT true,
    ultimo_acesso TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_usuarios_email UNIQUE (email)
);

CREATE TABLE public.permissoes (
    id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    perfil    perfil_usuario_enum NOT NULL,
    recurso   TEXT NOT NULL,
    acao      TEXT NOT NULL CHECK (acao IN ('ler','criar','editar','excluir','cancelar','estornar','exportar')),
    permitido BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT uq_permissoes UNIQUE (perfil, recurso, acao)
);
CREATE INDEX idx_permissoes_perfil ON public.permissoes (perfil, recurso);

CREATE TABLE public.categorias (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL CHECK (length(trim(nome)) BETWEEN 2 AND 80),
    descricao TEXT, ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.usuarios(id),
    updated_by UUID REFERENCES public.usuarios(id),
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_categorias_nome ON public.categorias (public.fn_norm(nome)) WHERE deleted_at IS NULL;

CREATE TABLE public.marcas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL CHECK (length(trim(nome)) BETWEEN 2 AND 80),
    ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.usuarios(id),
    updated_by UUID REFERENCES public.usuarios(id),
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_marcas_nome ON public.marcas (public.fn_norm(nome)) WHERE deleted_at IS NULL;

CREATE TABLE public.fornecedores (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL CHECK (length(trim(nome)) BETWEEN 2 AND 150),
    documento TEXT, telefone TEXT, whatsapp TEXT,
    email TEXT CHECK (email IS NULL OR email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    cidade TEXT, estado CHAR(2) CHECK (estado IS NULL OR estado ~ '^[A-Z]{2}$'),
    endereco TEXT, observacoes TEXT, ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.usuarios(id),
    updated_by UUID REFERENCES public.usuarios(id),
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_fornecedores_doc ON public.fornecedores (documento) WHERE documento IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX idx_fornecedores_nome ON public.fornecedores USING gin (public.fn_norm(nome) extensions.gin_trgm_ops);

CREATE TABLE public.clientes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome TEXT NOT NULL CHECK (length(trim(nome)) BETWEEN 2 AND 150),
    cpf TEXT CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$'),
    telefone TEXT CHECK (telefone IS NULL OR telefone ~ '^[0-9]{10,11}$'),
    whatsapp TEXT CHECK (whatsapp IS NULL OR whatsapp ~ '^[0-9]{10,11}$'),
    email TEXT CHECK (email IS NULL OR email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    data_nascimento DATE,
    cep TEXT CHECK (cep IS NULL OR cep ~ '^[0-9]{8}$'),
    endereco TEXT, numero TEXT, complemento TEXT, bairro TEXT,
    cidade TEXT, estado CHAR(2) CHECK (estado IS NULL OR estado ~ '^[A-Z]{2}$'),
    observacoes TEXT, ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.usuarios(id),
    updated_by UUID REFERENCES public.usuarios(id),
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_clientes_cpf ON public.clientes (cpf) WHERE cpf IS NOT NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX uq_clientes_codigo ON public.clientes (codigo);
CREATE INDEX idx_clientes_nome ON public.clientes USING gin (public.fn_norm(nome) extensions.gin_trgm_ops);

CREATE TABLE public.revendedores (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    codigo BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome TEXT NOT NULL CHECK (length(trim(nome)) BETWEEN 2 AND 150),
    cpf TEXT CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$'),
    telefone TEXT CHECK (telefone IS NULL OR telefone ~ '^[0-9]{10,11}$'),
    whatsapp TEXT CHECK (whatsapp IS NULL OR whatsapp ~ '^[0-9]{10,11}$'),
    email TEXT CHECK (email IS NULL OR email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    cep TEXT CHECK (cep IS NULL OR cep ~ '^[0-9]{8}$'),
    endereco TEXT, numero TEXT, complemento TEXT, bairro TEXT,
    cidade TEXT, estado CHAR(2) CHECK (estado IS NULL OR estado ~ '^[A-Z]{2}$'),
    data_cadastro DATE NOT NULL DEFAULT CURRENT_DATE,
    limite_credito NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (limite_credito >= 0),
    prazo_acerto_dias INTEGER NOT NULL DEFAULT 30 CHECK (prazo_acerto_dias BETWEEN 1 AND 365),
    observacoes TEXT, ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.usuarios(id),
    updated_by UUID REFERENCES public.usuarios(id),
    deleted_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_revendedores_cpf ON public.revendedores (cpf) WHERE cpf IS NOT NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX uq_revendedores_codigo ON public.revendedores (codigo);
CREATE INDEX idx_revendedores_nome ON public.revendedores USING gin (public.fn_norm(nome) extensions.gin_trgm_ops);

CREATE TABLE public.formas_pagamento (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome TEXT NOT NULL,
    permite_parcelar BOOLEAN NOT NULL DEFAULT false,
    max_parcelas SMALLINT NOT NULL DEFAULT 1 CHECK (max_parcelas BETWEEN 1 AND 4),
    taxa_percentual NUMERIC(7,4) NOT NULL DEFAULT 0 CHECK (taxa_percentual BETWEEN 0 AND 100),
    prazo_compensacao_dias SMALLINT NOT NULL DEFAULT 0 CHECK (prazo_compensacao_dias >= 0),
    ativo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_formas_pagamento_nome UNIQUE (nome),
    CONSTRAINT chk_forma_parcelamento CHECK (
      (permite_parcelar AND max_parcelas > 1) OR (NOT permite_parcelar AND max_parcelas = 1))
);
