CREATE TABLE public.titulos_receber (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    numero BIGINT GENERATED BY DEFAULT AS IDENTITY,
    origem origem_titulo_enum NOT NULL,
    venda_id UUID REFERENCES public.vendas(id) ON DELETE RESTRICT,
    prestacao_id UUID REFERENCES public.prestacoes_contas(id) ON DELETE RESTRICT,
    tipo_devedor tipo_devedor_enum NOT NULL,
    cliente_id UUID REFERENCES public.clientes(id) ON DELETE RESTRICT,
    revendedor_id UUID REFERENCES public.revendedores(id) ON DELETE RESTRICT,
    numero_parcela SMALLINT NOT NULL DEFAULT 1 CHECK (numero_parcela BETWEEN 1 AND 4),
    total_parcelas SMALLINT NOT NULL DEFAULT 1 CHECK (total_parcelas BETWEEN 1 AND 4),
    valor_original NUMERIC(14,2) NOT NULL CHECK (valor_original > 0),
    valor_recebido NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (valor_recebido >= 0),
    saldo NUMERIC(14,2) GENERATED ALWAYS AS (valor_original - valor_recebido) STORED,
    data_emissao DATE NOT NULL DEFAULT CURRENT_DATE,
    data_vencimento DATE NOT NULL,
    data_quitacao DATE,
    situacao situacao_titulo_enum NOT NULL DEFAULT 'ABERTO',
    lucro_proporcional NUMERIC(14,2) NOT NULL DEFAULT 0,
    observacoes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.usuarios(id),
    updated_by UUID REFERENCES public.usuarios(id),
    CONSTRAINT uq_titulos_numero UNIQUE (numero),
    CONSTRAINT chk_titulo_origem CHECK (
        (origem='VENDA' AND venda_id IS NOT NULL AND prestacao_id IS NULL)
     OR (origem='PRESTACAO_CONTAS' AND prestacao_id IS NOT NULL AND venda_id IS NULL)
     OR (origem='AVULSO' AND venda_id IS NULL AND prestacao_id IS NULL)),
    CONSTRAINT chk_titulo_devedor CHECK (
        (tipo_devedor='CLIENTE' AND revendedor_id IS NULL)
     OR (tipo_devedor='REVENDEDOR' AND revendedor_id IS NOT NULL AND cliente_id IS NULL)),
    CONSTRAINT chk_titulo_devedor_identificado CHECK (
        situacao <> 'ABERTO' OR cliente_id IS NOT NULL OR revendedor_id IS NOT NULL),
    CONSTRAINT chk_titulo_parcela CHECK (numero_parcela <= total_parcelas),
    CONSTRAINT chk_titulo_recebido CHECK (valor_recebido <= valor_original),
    CONSTRAINT chk_titulo_vencimento CHECK (data_vencimento >= data_emissao),
    CONSTRAINT chk_titulo_quitacao CHECK (
        (situacao='PAGO' AND data_quitacao IS NOT NULL)
     OR (situacao<>'PAGO' AND data_quitacao IS NULL))
);
CREATE UNIQUE INDEX uq_titulo_venda_parcela ON public.titulos_receber (venda_id, numero_parcela) WHERE venda_id IS NOT NULL;
CREATE UNIQUE INDEX uq_titulo_prestacao_parcela ON public.titulos_receber (prestacao_id, numero_parcela) WHERE prestacao_id IS NOT NULL;
CREATE INDEX idx_titulos_vencimento ON public.titulos_receber (data_vencimento) WHERE situacao='ABERTO';
CREATE INDEX idx_titulos_cliente ON public.titulos_receber (cliente_id, situacao, data_vencimento);
CREATE INDEX idx_titulos_revendedor ON public.titulos_receber (revendedor_id, situacao, data_vencimento);
CREATE INDEX idx_titulos_venda ON public.titulos_receber (venda_id);
CREATE INDEX idx_titulos_prestacao ON public.titulos_receber (prestacao_id);
CREATE INDEX idx_titulos_situacao ON public.titulos_receber (situacao, tipo_devedor);

CREATE TABLE public.recebimentos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    numero BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_devedor tipo_devedor_enum NOT NULL,
    cliente_id UUID REFERENCES public.clientes(id) ON DELETE RESTRICT,
    revendedor_id UUID REFERENCES public.revendedores(id) ON DELETE RESTRICT,
    data_recebimento DATE NOT NULL DEFAULT CURRENT_DATE,
    valor_total NUMERIC(14,2) NOT NULL CHECK (valor_total > 0),
    valor_alocado NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (valor_alocado >= 0),
    forma_pagamento_id UUID NOT NULL REFERENCES public.formas_pagamento(id) ON DELETE RESTRICT,
    comprovante_url TEXT,
    estornado BOOLEAN NOT NULL DEFAULT false,
    data_estorno TIMESTAMPTZ, motivo_estorno TEXT, observacoes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.usuarios(id),
    CONSTRAINT uq_recebimentos_numero UNIQUE (numero),
    CONSTRAINT chk_receb_devedor CHECK (
        (tipo_devedor='CLIENTE' AND revendedor_id IS NULL)
     OR (tipo_devedor='REVENDEDOR' AND revendedor_id IS NOT NULL AND cliente_id IS NULL)),
    CONSTRAINT chk_receb_alocado CHECK (valor_alocado <= valor_total),
    CONSTRAINT chk_receb_estorno CHECK (NOT estornado
      OR (data_estorno IS NOT NULL AND motivo_estorno IS NOT NULL))
);
CREATE INDEX idx_receb_data ON public.recebimentos (data_recebimento DESC);
CREATE INDEX idx_receb_cliente ON public.recebimentos (cliente_id, data_recebimento DESC);
CREATE INDEX idx_receb_revendedor ON public.recebimentos (revendedor_id, data_recebimento DESC);
CREATE INDEX idx_receb_ativos ON public.recebimentos (data_recebimento) WHERE NOT estornado;
CREATE INDEX idx_receb_forma ON public.recebimentos (forma_pagamento_id);

CREATE TABLE public.recebimento_alocacoes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recebimento_id UUID NOT NULL REFERENCES public.recebimentos(id) ON DELETE CASCADE,
    titulo_id UUID NOT NULL REFERENCES public.titulos_receber(id) ON DELETE RESTRICT,
    valor NUMERIC(14,2) NOT NULL CHECK (valor > 0),
    estornada BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.usuarios(id),
    CONSTRAINT uq_alocacao UNIQUE (recebimento_id, titulo_id)
);
CREATE INDEX idx_alocacoes_titulo ON public.recebimento_alocacoes (titulo_id) WHERE NOT estornada;
CREATE INDEX idx_alocacoes_recebimento ON public.recebimento_alocacoes (recebimento_id);

CREATE TABLE public.despesas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    numero BIGINT GENERATED BY DEFAULT AS IDENTITY,
    categoria categoria_despesa_enum NOT NULL,
    natureza natureza_despesa_enum NOT NULL DEFAULT 'VARIAVEL',
    descricao TEXT NOT NULL CHECK (length(trim(descricao)) >= 3),
    valor NUMERIC(14,2) NOT NULL CHECK (valor > 0),
    data_despesa DATE NOT NULL DEFAULT CURRENT_DATE,
    data_pagamento DATE,
    produto_id UUID REFERENCES public.produtos(id) ON DELETE SET NULL,
    origem_tabela TEXT, origem_id UUID,
    forma_pagamento_id UUID REFERENCES public.formas_pagamento(id) ON DELETE RESTRICT,
    comprovante_url TEXT,
    recorrente BOOLEAN NOT NULL DEFAULT false,
    observacoes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by UUID REFERENCES public.usuarios(id),
    updated_by UUID REFERENCES public.usuarios(id),
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_despesas_numero UNIQUE (numero),
    CONSTRAINT chk_despesa_pagamento CHECK (data_pagamento IS NULL OR data_pagamento >= data_despesa)
);
CREATE INDEX idx_despesas_data ON public.despesas (data_despesa DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_despesas_categoria ON public.despesas (categoria, data_despesa DESC);
CREATE INDEX idx_despesas_produto ON public.despesas (produto_id);
CREATE INDEX idx_despesas_forma ON public.despesas (forma_pagamento_id);
CREATE INDEX idx_despesas_origem ON public.despesas (origem_tabela, origem_id);

CREATE TABLE public.logs_auditoria (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    usuario_id UUID REFERENCES public.usuarios(id) ON DELETE SET NULL,
    usuario_nome TEXT,
    acao acao_auditoria_enum NOT NULL,
    tabela TEXT NOT NULL,
    registro_id UUID,
    registro_descricao TEXT,
    dados_anteriores JSONB, dados_novos JSONB,
    campos_alterados TEXT[],
    ip INET, user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_logs_data ON public.logs_auditoria (created_at DESC);
CREATE INDEX idx_logs_tabela ON public.logs_auditoria (tabela, registro_id);
CREATE INDEX idx_logs_usuario ON public.logs_auditoria (usuario_id, created_at DESC);
CREATE INDEX idx_logs_acao ON public.logs_auditoria (acao, created_at DESC);

CREATE TABLE public.parametros (
    chave TEXT PRIMARY KEY,
    valor TEXT NOT NULL,
    tipo TEXT NOT NULL DEFAULT 'texto' CHECK (tipo IN ('texto','numero','booleano','data','json')),
    descricao TEXT NOT NULL,
    grupo TEXT NOT NULL DEFAULT 'geral',
    editavel BOOLEAN NOT NULL DEFAULT true,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by UUID REFERENCES public.usuarios(id)
);

CREATE TABLE public.notificacoes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tipo tipo_notificacao_enum NOT NULL,
    severidade severidade_enum NOT NULL DEFAULT 'INFO',
    titulo TEXT NOT NULL, mensagem TEXT NOT NULL,
    referencia_tabela TEXT, referencia_id UUID,
    usuario_id UUID REFERENCES public.usuarios(id) ON DELETE CASCADE,
    lida BOOLEAN NOT NULL DEFAULT false,
    data_referencia DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_notificacao UNIQUE NULLS NOT DISTINCT
      (tipo, referencia_tabela, referencia_id, data_referencia)
);
CREATE INDEX idx_notif_nao_lidas ON public.notificacoes (created_at DESC) WHERE NOT lida;
CREATE INDEX idx_notif_tipo ON public.notificacoes (tipo, created_at DESC);
CREATE INDEX idx_notif_usuario ON public.notificacoes (usuario_id);
